In [2]:
import torch
import torch.nn as nn
import numpy as np

In [2]:
torch.zeros(1, 2)

tensor([[0., 0.]])

In [ ]:
torch.rand(2, 3)

In [23]:
x = np.array([1, 2, 3, 4], dtype=np.float32)
y = np.array([2, 4, 6, 8], dtype=np.float32)

In [24]:
x, y

(array([1., 2., 3., 4.], dtype=float32),
 array([2., 4., 6., 8.], dtype=float32))

In [25]:
w = 1.1
b = 1
lr = 0.001
alpha = 0.0001

In [26]:
def forward(x):
    return (x*w)

In [27]:
def loss(y_pred, y_real):
    return ((y_pred - y_real)**2).mean()

In [28]:
def gradient(x, y_pred, y):
    return np.mean(2*x*y_pred - y)
#     return np.diff(dinputs)

In [29]:
def update_weights(w, grad, lr=0.0001):
    return w-lr*grad

In [30]:
def update_lr(lr, alpha):
    return lr-alpha

In [40]:
def train(x, y, w, lr, epochs=10):
    weight = w
    learning_rate = lr
    for i in range(epochs):
        y_hat = forward(x)
        final_loss = loss(y_hat, y)
        grad = gradient(x, y_hat, y)
        w = update_weights(weight, grad, learning_rate)
        learning_rate = update_lr(learning_rate, alpha)
    return weight, lr

In [41]:
y_pred = forward(x)

gradient(x, y_pred, y)

10.5512495

In [42]:
w, lr = train(x, y, w, lr)

In [43]:
forward(x)

array([1.03675, 2.0735 , 3.11025, 4.147  ], dtype=float32)

In [72]:
import torch

x = torch.randn(3, requires_grad=True)

In [73]:
x

tensor([ 0.7873,  0.3611, -0.4414], requires_grad=True)

In [74]:
y = x + 2

In [75]:
y

tensor([2.7873, 2.3611, 1.5586], grad_fn=<AddBackward0>)

In [76]:
y.grad_fn(y)

(tensor([2.7873, 2.3611, 1.5586], grad_fn=<AddBackward0>), None)

In [77]:
y.backward(x)

In [78]:
y

tensor([2.7873, 2.3611, 1.5586], grad_fn=<AddBackward0>)

In [87]:
x = torch.tensor([1, 2, 3, 4], dtype=torch.float32)
y = torch.tensor([2, 4, 6, 8], dtype=torch.float32)

In [88]:
w = torch.tensor(0.0, dtype=torch.float32, requires_grad=True)
learning_rate = 0.01
n_iters = 100

In [69]:
for epoch in range(n_iters):
    y_pred = forward(x)
    
    l = loss(y, y_pred)
    
    l.backward()
    
    with torch.no_grad():
        w -= learning_rate*w.grad
    
    w.grad.zero_()
    
    if epoch % 10 == 0:
        print(f'epoch {epoch+1}: w={w}')

epoch 1: w=0.29999998211860657
epoch 11: w=1.6653136014938354
epoch 21: w=1.934108853340149
epoch 31: w=1.987027645111084
epoch 41: w=1.9974461793899536
epoch 51: w=1.9994971752166748
epoch 61: w=1.9999010562896729
epoch 71: w=1.9999804496765137
epoch 81: w=1.999996304512024
epoch 91: w=1.9999992847442627


In [89]:
loss = nn.MSELoss()
optimizer = torch.optim.SGD([w], lr=learning_rate)

In [90]:
for epoch in range(n_iters):
    y_pred = forward(x)
    
    l = loss(y, y_pred)
    
    l.backward()
    
    optimizer.step()
    
    optimizer.zero_grad()

    if epoch % 10 == 0:
        print(f'epoch {epoch+1}: w={w}')

epoch 1: w=0.29999998211860657
epoch 11: w=1.6653136014938354
epoch 21: w=1.934108853340149
epoch 31: w=1.987027645111084
epoch 41: w=1.9974461793899536
epoch 51: w=1.9994971752166748
epoch 61: w=1.9999010562896729
epoch 71: w=1.9999804496765137
epoch 81: w=1.999996304512024
epoch 91: w=1.9999992847442627


In [9]:
X = torch.tensor([[1], [2], [3], [4]], dtype=torch.float32)
Y = torch.tensor([[2], [4], [6], [8]], dtype=torch.float32)

n_samples, n_features = X.shape

X_test = torch.tensor([5], dtype=torch.float32)
input_size = n_features
output_size = n_features

In [10]:
model = nn.Linear(input_size, output_size)

In [11]:
learning_rate = 0.1
n_iters = 100

loss = nn.MSELoss()
optimizers = torch.optim.SGD(model.parameters(), lr=learning_rate)

for epoch in range(n_iters):
    y_pred = model(X)
    
    l = loss(Y, y_pred)
    
    l.backward()
    
    optimizers.step()
    
    optimizers.zero_grad()
    
    if epoch % 10 == 0:
        [w, b] = model.parameters()
        print(f"Epoch {epoch+1}: w={w[0][0].item()}, loss={l}")

Epoch 1: w=2.073657751083374, loss=4.4922919273376465
Epoch 11: w=1.727867841720581, loss=0.12205475568771362
Epoch 21: w=1.7932403087615967, loss=0.06568250805139542
Epoch 31: w=1.8473259210586548, loss=0.03576245531439781
Epoch 41: w=1.8873416185379028, loss=0.019471921026706696
Epoch 51: w=1.9168707132339478, loss=0.010602024383842945
Epoch 61: w=1.938659906387329, loss=0.005772573873400688
Epoch 71: w=1.954737901687622, loss=0.0031430423259735107
Epoch 81: w=1.9666017293930054, loss=0.0017113133799284697
Epoch 91: w=1.975355863571167, loss=0.0009317751391790807


In [12]:
!pip install open-nn-python

Defaulting to user installation because normal site-packages is not writeable


In [21]:
import nn

In [22]:
model = nn.models.Sequential()

In [23]:
model.add(nn.layers.Layer_Dense(4, 128, activation=nn.activations.ReLU()))

3

In [24]:
model.add(nn.layers.Layer_Dense(128, 4, activation=nn.activations.ReLU()))

4

In [25]:
model.fit(X, Y, epoch=10)

ValueError: shapes (4,1) and (128,128) not aligned: 1 (dim 1) != 128 (dim 0)